---
- name: Настройка сервера Debian 10 и установка PostgreSQL
  hosts: debian_server
  become: true
  tasks:

    - name: Update packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Install python3,python3-pip, libpq-dev
      apt:
        name:
          - python3
          - python3-pip
          - libpq-dev
        state: present

    - name: Make sure psycopg2 is installed
      pip:
        name: psycopg2
        state: present


    - name: Is PostgreSQL Started?
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Open port for PostgreSQL
      ufw:
        rule: allow
        port: 5432
        proto: tcp

    - name: Install SSH
      apt:
        name: ssh
        state: present

    - name: Is SSH Started?
      service:
        name: ssh
        state: started
        enabled: true

    - name: Setup SSH - Disable root enter
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
        backup: yes
      notify: Restart SSH

    - name: Open port for SSH
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Initialize PostgreSQL Database
      become_user: postgres
      postgresql_db:
        name: test

    - name: Create PostgreSQL user
      become_user: postgres
      postgresql_user:
        name: userok
        password: userok123

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
        